name: Deploy Storage
run-name: Deploy Databricks

on:
  workflow_call:
    inputs:
      resource_group_name:
        description: "Name of resource group that contains the storage account"
        required: true
        type: string
      storage_account_name:
        description: "Name of the storage account"
        required: true
        type: string
      storage_content_file_path:
        description: "Name of the storage content list path"
        required: true
        type: string
      environment:
        description: "Environment name e.g. (dev, qa, prod)"
        required: true
        type: string
    secrets:
      client_id:
        description: "Client ID of the SPN used to login to azure using OIDC"
        required: true
      tenant_id:
        description: "Azure Active Directory Tenant ID"
        required: true
      subscription_id:
        description: "Subscription ID of the subscription containing the ADF"
        required: true
    # # Map the workflow outputs to job outputs
    # outputs:
    #   workflow_output1:
    #     description: "The first job output"
    #     value: ${{ jobs.my_job.outputs.job_output1 }}
    #   workflow_output2:
    #     description: "The second job output"
    #     value: ${{ jobs.my_job.outputs.job_output2 }}

permissions:
  id-token: write
  contents: read

jobs:
  configure_storage:
    name: Configure Storage

    runs-on:
      group: linux-x64

    environment: "${{ inputs.environment }}"

    steps:
      - name: Checkout [onelake-adf] Repo
        uses: actions/checkout@v4
      
        # Output all inputs
      - name: Display workflow inputs
        run: echo "${{ toJSON(inputs) }}"

      - name: Azure Login using OIDC
        uses: ./.github/workflows/composite/az-oidc-login
        with:
          tenant_id: ${{ secrets.tenant_id }}
          subscription_id: ${{ secrets.subscription_id }}
          client_id: ${{ secrets.client_id }}
          enable_az_ps_session: true

      - name: Install PowerShell Modules
        shell: pwsh
        run: |
          ./.github/artifacts/cicd/scripts/install-modules.ps1

      - name: Configure Storage Account
        shell: pwsh
        # env:
        #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   # AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        #   # AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          ./.github/artifacts/cicd/scripts/setup-storage.ps1 -StorageAccountName "${{ inputs.storage_account_name }}" -StorageAccountResourceGroupName "${{ inputs.resource_group_name }}" -StorageContentFilePath "${{ inputs.storage_content_file_path }}"
